name: CI
on:
  push:
    branches: ["main"]
  pull_request:

env:
  PYTHONPATH: ${{ github.workspace }}
  MONGO_URI: ${{ secrets.MONGO_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install fastapi uvicorn[standard] pymongo python-dotenv pydantic-settings passlib[bcrypt] pyjwt
          pip install ruff black mypy pytest
      - name: Lint (ruff)
        run: |
          . .venv/bin/activate
          ruff check .
          ruff check . --fix
      - name: Format check (black)
        run: |
          . .venv/bin/activate
          black --check .
      - name: Type check (mypy)
        run: |
          . .venv/bin/activate
          mypy app
      - name: Tests
        run: |
          . .venv/bin/activate
          pytest -q
      - name: Ruff (auto-fix imports)
        run: |
         pip install ruff
         ruff check --select I --fix .
      - name: Install deps (Poetry)
        run: |
         . .venv/bin/activate
         python -m pip install --upgrade pip
         pip install -r requirements.txt 
      - name: Sanity check deps (must print httpx version)
        run: |
          . .venv/bin/activate
          python -c "import httpx, sys; print('httpx:', httpx.__version__, 'python:', sys.version)"
          pip freeze

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          # If your tests need a real DB, add the secret in repo settings and uncomment:
          # MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          . .venv/bin/activate
          pytest -q
