name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install fastapi "uvicorn[standard]" pymongo pytest httpx python-multipart pydantic itsdangerous email-validator
          fi

      - name: Run tests
        env:
          USE_INMEMORY_QC: '1'
          MONGO_URI: 'mongodb://invalid:27017'
          DB_NAME: 'trishul'
        run: pytest -q

  frontend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./prototype/ui

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './prototype/ui/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Check Prettier formatting
      run: npm run format:check

    - name: Build application
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: ./prototype/ui/dist/
        retention-days: 7
