jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create venv & install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          # Install all deps including httpx from your requirements.txt
          pip install -r requirements.txt
          # (Optional) If you have extra dev tools not in requirements.txt:
          pip install ruff black mypy

      - name: Sanity check deps (must print httpx version)
        run: |
          . .venv/bin/activate
          python -c "import httpx, sys; print('httpx:', httpx.__version__, 'python:', sys.version)"
          pip freeze

      - name: Lint (ruff)
        run: |
          . .venv/bin/activate
          ruff check .
          ruff check . --fix

      - name: Format check (black)
        run: |
          . .venv/bin/activate
          black --check .

      - name: Type check (mypy)
        run: |
          . .venv/bin/activate
          mypy app

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          MONGO_URI: ${{ secrets.MONGO_URI }}  # leave blank if your code is lazy-loading the client
        run: |
          . .venv/bin/activate
          pytest -q
