name: CI
on:
  push:
    branches: ["main"]
  pull_request:

env:
  PYTHONPATH: ${{ github.workspace }}
  MONGO_URI: ${{ secrets.MONGO_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install fastapi uvicorn[standard] pymongo python-dotenv pydantic-settings passlib[bcrypt] pyjwt
          pip install ruff black mypy pytest httpx 

      - name: Code checks and tests
        run: |
          # Activate the virtual environment
          . .venv/bin/activate
          
          # Run linting (ruff)
          echo "Running Ruff checks..."
          ruff check . --fix # The --fix flag modifies files
          ruff check . # Re-run check to ensure there are no remaining errors
          
          # Run format check (black)
          echo "Running Black format check..."
          black --check .
          
          # Run type check (mypy)
          echo "Running MyPy type check..."
          mypy app
          
          # Run tests
          echo "Running Pytest..."
          pytest -q
